repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: just lint
        language: system
        pass_filenames: false
      - id: mypy
        name: static analysis
        entry: just static
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: just test
        language: system
        pass_filenames: false
        always_run: true
